webrtc-sys/build.rs, webrtc-sys/libwebrtc/configure.py
=> allow custom webrtc builds

examples/simple_room/src/app.rs, examples/simple_room/src/events.rs
- Add participant names
- Listen to TrackUnsubscribed
- Show info about the room
- Disconnect btn
- Correctly close the task
=> simple_room: improvements & bug fixes

.cargo/config, webrtc-sys/build.rs, webrtc-sys/include/livekit/objc_video_factory.h, webrtc-sys/include/livekit/video_decoder_factory.h, webrtc-sys/include/livekit/video_encoder_factory.h, webrtc-sys/src/objc_video_factory.mm, webrtc-sys/src/peer_connection_factory.cpp, webrtc-sys/src/video_decoder_factory.cpp, webrtc-sys/src/video_encoder_factory.cpp
- Created `livekit::VideoEncoderFactory` to use multiple factories at the same time.
We'll add future hw encoders here
- Added VideoToolBox
=> VideoToolBox decoder/encoder for MacOS & iOS

livekit-ffi/protocol/ffi.proto, livekit-ffi/src/server/conversion.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/room.rs, livekit-webrtc/src/media_stream.rs, livekit-webrtc/src/prelude.rs, livekit-webrtc/src/video_frame_buffer.rs, livekit-webrtc/src/yuv_helper.rs, livekit/src/prelude.rs, livekit/src/room/mod.rs, livekit/src/room/publication/mod.rs, livekit/src/room/room_session.rs, webrtc-sys/include/livekit/yuv_helper.h, webrtc-sys/src/yuv_helper.rs
For the current Rust SDK features.
Publishing tracks will be on another PR
=> finish proto of livekit-ffi

Cargo.lock, webrtc-sys/Cargo.toml, webrtc-sys/build.rs
Curl crate fails 2/3 computers I use when not configured.
=> Use reqwest instead of curl to download libwebrtc

examples/simple_room/src/app.rs, examples/simple_room/src/events.rs, examples/simple_room/src/logo_track.rs, examples/simple_room/src/main.rs, examples/simple_room/src/sine_track.rs, livekit-webrtc/src/audio_frame.rs, livekit-webrtc/src/audio_source.rs, livekit-webrtc/src/audio_stream.rs, livekit-webrtc/src/lib.rs, livekit-webrtc/src/native/audio_source.rs, livekit-webrtc/src/native/audio_stream.rs, livekit-webrtc/src/native/mod.rs, livekit-webrtc/src/native/peer_connection_factory.rs, livekit-webrtc/src/native/rtp_transceiver.rs, livekit-webrtc/src/peer_connection_factory.rs, livekit-webrtc/src/prelude.rs, livekit/src/room/options.rs, livekit/src/room/participant/local_participant.rs, livekit/src/room/track/local_audio_track.rs, livekit/src/room/track/local_video_track.rs, livekit/src/rtc_engine/rtc_session.rs, webrtc-sys/build.rs, webrtc-sys/include/livekit/audio_device.h, webrtc-sys/include/livekit/media_stream.h, webrtc-sys/include/livekit/peer_connection_factory.h, webrtc-sys/src/audio_device.cpp, webrtc-sys/src/media_stream.cpp, webrtc-sys/src/media_stream.rs, webrtc-sys/src/peer_connection_factory.cpp, webrtc-sys/src/peer_connection_factory.rs
- Receive/Send audio frames
- LocalAudioTrack
=> feat: audio support

.github/workflows/builds.yml, Cargo.toml
Waiting for the ring crate to release v0.17 (jsonwebtokens needs to update it)
=> disable livekit-api builds for windows aarch64

examples/Cargo.lock, examples/save_to_disk/Cargo.toml, examples/save_to_disk/src/main.rs, livekit-ffi/src/server/audio_frame.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/room.rs, livekit-ffi/src/server/video_frame.rs, webrtc-sys/src/audio_device.cpp
- save_to_disk example: write raw pcm frames into a wav file
=> fix bad audio quality & save_to_disk example

.github/workflows/builds.yml, .github/workflows/ffi-builds.yml, .github/workflows/tests.yml, Cargo.lock, examples/Cargo.lock, examples/basic_room/Cargo.toml, examples/basic_room/src/main.rs, livekit-webrtc/Cargo.toml, livekit-webrtc/src/native/peer_connection_factory.rs, livekit/Cargo.toml, livekit/src/room/track/local_audio_track.rs, livekit/src/room/track/local_video_track.rs, livekit/src/rtc_engine/lk_runtime.rs, livekit/src/rtc_engine/rtc_session.rs, webrtc-sys/build.rs, webrtc-sys/include/livekit/logsink.h, webrtc-sys/src/lib.rs, webrtc-sys/src/logsink.cpp, webrtc-sys/src/logsink.rs
note: libwebrtc info logs are translated to debug to avoid polluting the user logs.
=> feat: forward libwebrtc logs

webrtc-sys/libwebrtc/build_android.sh, webrtc-sys/libwebrtc/build_ios.sh, webrtc-sys/libwebrtc/build_linux.sh, webrtc-sys/libwebrtc/build_macos.sh, webrtc-sys/libwebrtc/build_windows.cmd, webrtc-sys/libwebrtc/patches/add_licenses.patch
add openh264 and ffmpeg licenses
=> fix: webrtc licenses generation

webrtc-sys/build.rs
this enable h264 for linux & windows
=> feat: use new webrtc builds

Cargo.lock, livekit-ffi/Cargo.toml, livekit-ffi/src/server/tests.rs
=> fix: win-aarch64 ffi builds

livekit-ffi/src/conversion/room.rs, livekit-ffi/src/server/room.rs
Forgot to fire the event on the room
=> feat: ffi data received event

livekit-ffi/.cargo/config
optimize livekit-ffi for size (instead of speed)
Reduction of 50-75% for most of the platforms
https://github.com/livekit/client-sdk-rust/actions/runs/5447909603
=> feat: optimize livekit-ffi for size

webrtc-sys/include/livekit/android.h, webrtc-sys/src/android.cpp, webrtc-sys/src/video_decoder_factory.cpp, webrtc-sys/src/video_encoder_factory.cpp
=> feat: android hw mediacodec

webrtc-sys/src/video_decoder_factory.cpp, webrtc-sys/src/video_encoder_factory.cpp
Don't include android files on other platforms
=> fix: desktop builds

.github/workflows/webrtc-builds.yml, webrtc-sys/build.rs, webrtc-sys/libwebrtc/.gitignore, webrtc-sys/libwebrtc/build_android.sh, webrtc-sys/libwebrtc/build_ios.sh
- also remove webrtc debug builds
- fix ios and android webrtc licenses
=> feat: android with libc++_static

livekit/src/room/participant/remote_participant.rs, livekit/src/room/publication/remote.rs
- fix deadlock on subscription change
- fix TrackUnsubscribed event not being fired
=> fix: manual subscription

examples/wgpu_room/src/service.rs, livekit-ffi/protocol/ffi.proto, livekit-ffi/protocol/room.proto, livekit-ffi/src/conversion/room.rs, livekit-ffi/src/livekit.proto.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/room.rs, livekit/src/prelude.rs, livekit/src/room/mod.rs, livekit/src/room/participant/mod.rs, livekit/src/room/publication/remote.rs
- also add the set_subscribed method
=> feat: support more events on the ffi

Cargo.lock, examples/Cargo.lock, examples/basic_room/Cargo.toml, examples/wgpu_room/Cargo.toml, livekit-api/Cargo.toml, livekit-ffi/Cargo.toml, livekit-ffi/protocol/room.proto, livekit-ffi/protocol/video_frame.proto, livekit-ffi/src/conversion/video_frame.rs, livekit-ffi/src/livekit.proto.rs, livekit-ffi/src/server/requests.rs, livekit-ffi/src/server/room.rs, livekit-ffi/src/server/video_stream.rs, livekit-protocol/Cargo.toml, livekit-webrtc/Cargo.toml, livekit/Cargo.toml, webrtc-sys/Cargo.toml, webrtc-sys/build/Cargo.toml
- Ensure the PublishTrack async callback is **always sent** before the LocalTrackPublish event, so we don't have to synchronise anything on the ffi client
- Also avoid to use explicit dependencies version (avoid conflicts)
=> fix: synchronise publish events on the ffi

webrtc-sys/libwebrtc/.gitignore, webrtc-sys/libwebrtc/build_android.sh, webrtc-sys/libwebrtc/build_ios.sh, webrtc-sys/libwebrtc/build_linux.sh, webrtc-sys/libwebrtc/build_macos.sh, webrtc-sys/libwebrtc/build_windows.cmd, webrtc-sys/libwebrtc/patches/windows_silence_warnings.patch
match the version used by our cxx bindings
=> use c++20 on webrtc builds

Cargo.lock, livekit-webrtc/Cargo.toml, livekit-webrtc/src/audio_stream.rs, livekit-webrtc/src/native/audio_stream.rs, livekit-webrtc/src/native/peer_connection.rs, livekit-webrtc/src/native/video_stream.rs, livekit-webrtc/src/video_stream.rs
One of the two channel was dropped, and in a wrong timing, the dropped one was selected
=> fix: cancelled negotation

examples/Cargo.lock, livekit-ffi/src/server/audio_stream.rs, livekit-ffi/src/server/room.rs, livekit-ffi/src/server/video_stream.rs, livekit/src/room/mod.rs, livekit/src/room/participant/local_participant.rs, livekit/src/room/participant/remote_participant.rs, livekit/src/room/track/mod.rs, livekit/src/rtc_engine/lk_runtime.rs, livekit/src/rtc_engine/mod.rs, livekit/src/rtc_engine/peer_transport.rs, livekit/src/rtc_engine/rtc_session.rs
Synchronous blocking could happens due to libwebrtc. Log them since this is wrong 
Monitored:
- room_task
- engine_task
- rtc_task 
- signal_task
=> feat: add more logs & monitor stuck tasks 

.github/workflows/ffi-builds.yml, Cargo.lock
arm runners are ofter unavailable, so use a more powerful runner and qemu
=> use qemu for arm builds

Cargo.lock, livekit/src/room/mod.rs
ParticipantConnected was fired after TrackPublished
=> fix: published_track order

Cargo.lock, examples/wgpu_room/src/app.rs, examples/wgpu_room/src/logo_track.rs, libwebrtc/src/native/video_frame.rs, libwebrtc/src/native/video_source.rs, libwebrtc/src/prelude.rs, libwebrtc/src/video_frame.rs, libwebrtc/src/video_source.rs, livekit-ffi/protocol/ffi.proto, livekit-ffi/protocol/track.proto, livekit-ffi/src/conversion/stats.rs, livekit-ffi/src/conversion/video_frame.rs, livekit-ffi/src/livekit.proto.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/requests.rs, livekit-ffi/src/server/video_source.rs, webrtc-sys/include/livekit/frame_cryptor.h, webrtc-sys/include/livekit/jsep.h, webrtc-sys/include/livekit/peer_connection.h, webrtc-sys/src/jsep.cpp, webrtc-sys/src/peer_connection.cpp, webrtc-sys/src/peer_connection_factory.rs
- renamed VideoFrameBuffer to VideoBuffer
- also show speaking indicator inside the demo 
- added GetStatsRequest
=> feat: stats request

libwebrtc/src/native/video_frame.rs
I was going through the src code and noticed a minor typo.
=> chore: fix minor comment typo

README.md
updates https://github.com/livekit/rust-sdks/pull/236
=> chore: update 'Receive video frames of a subscribed track' docs

.github/workflows/webrtc-builds.yml, webrtc-sys/libwebrtc/build_linux.sh, webrtc-sys/libwebrtc/build_windows.cmd
=> fix h264 by adding ffmpeg_branding

livekit-ffi/protocol/ffi.proto, livekit-ffi/src/livekit.proto.rs, livekit-ffi/src/server/logger.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/requests.rs
forward logs to the ffi c.lient
=> feat: ffi logger

livekit-api/src/signal_client/signal_stream.rs, livekit-ffi/Cargo.toml, livekit-ffi/protocol/ffi.proto, livekit-ffi/src/cabi.rs, livekit-ffi/src/lib.rs, livekit-ffi/src/livekit.proto.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/requests.rs
- added callback_fn, so it can be used for NodeJS integration
=> allow other ffi integrations

.github/workflows/ffi-builds.yml, livekit-ffi/Cargo.toml
- Disable Windows for now (The builds are failing)
=> ffi v0.3.14

Cargo.lock, livekit-ffi/src/server/audio_stream.rs, livekit-ffi/src/server/video_stream.rs
Cloning the ffi_track instead of keeping the ReadGuard
=> fix deadlock when creating VideoStream and AudioStream

README.md
Add some useful info based on #277 and #249.
=> general: update README

download_ffi.py
python-sdks now directly use this file
=> update download_ffi.py to support cibuildwheel

livekit-ffi/src/server/audio_source.rs, livekit-ffi/src/server/requests.rs, livekit-ffi/src/server/room.rs, livekit-ffi/src/server/video_source.rs
- also enter the runtime inside ffi_request. (less errorprone)
=> copy ffi async requests data

livekit-ffi/src/server/audio_source.rs, livekit-ffi/src/server/audio_stream.rs, livekit-ffi/src/server/logger.rs, livekit-ffi/src/server/mod.rs, livekit-ffi/src/server/requests.rs, livekit-ffi/src/server/room.rs, livekit-ffi/src/server/video_stream.rs
useful when panicking, I'm now confident the Python side isn't blocking when receiving events so it is OK to log nothing now
=> sync send event

livekit-api/src/signal_client/signal_stream.rs
Ignore 
`[2024-05-06T16:18:00Z ERROR livekit_api::signal_client::signal_stream] unhandled websocket message Err(Protocol(ResetWithoutClosingHandshake))`
=> ignore ResetWithoutClosingHandshake log

livekit-api/src/signal_client/signal_stream.rs
=> Revert "ignore ResetWithoutClosingHandshake log"

Cargo.lock, libwebrtc/Cargo.toml, livekit-api/Cargo.toml, livekit-ffi/Cargo.toml, livekit-protocol/Cargo.toml, livekit/Cargo.toml
Nor very familiar with Rust crate release process, so please double-check this!
=> Release v0.3.4, v0.4.1

livekit/src/room/participant/remote_participant.rs, livekit/src/room/publication/remote.rs, livekit/src/room/track/local_audio_track.rs, livekit/src/room/track/local_video_track.rs, livekit/src/room/track/mod.rs, livekit/src/room/track/remote_audio_track.rs, livekit/src/room/track/remote_video_track.rs
=> livekit: send UpdateTrackSettings on disable

webrtc-sys/libwebrtc/build_android.sh, webrtc-sys/libwebrtc/build_ios.sh, webrtc-sys/libwebrtc/build_macos.sh, webrtc-sys/libwebrtc/build_windows.cmd
=> webrtc-sys: checkout m114 for everything

libwebrtc/Cargo.toml, livekit/Cargo.toml, webrtc-sys/Cargo.toml, webrtc-sys/build/Cargo.toml, webrtc-sys/build/src/lib.rs
cuts a release to fix https://livekit-users.slack.com/archives/C04G4GE0RGX/p1725226000547219
=> bump: webrtc-sys{,-build}, libwebrtc, livekit

livekit-ffi/Cargo.toml
minor bump for the proto2 syntax
=> ffi-v0.12.0

.github/workflows/ffi-builds.yml, .github/workflows/webrtc-builds.yml
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
=> ci: fix FFI and WebRTC builds with artifacts v4

.github/workflows/ffi-builds.yml, .github/workflows/webrtc-builds.yml
=> ci: fix missed line

.github/workflows/ffi-builds.yml, .github/workflows/tests.yml, .github/workflows/webrtc-builds.yml
related to https://github.com/livekit/rust-sdks/pull/578
=> update more gh runner images

libwebrtc/src/native/mod.rs, livekit-ffi/Cargo.toml, livekit-ffi/src/server/mod.rs, webrtc-sys/src/lib.rs
- release AudioProcessingModule
=> ffi-v0.13.0

.nanpa/stream-close.kdl, livekit-ffi/src/server/audio_stream.rs
This code really need cleanup..
=> fix rtc.AudioFrame.from_participant not closing

livekit/src/rtc_engine/rtc_session.rs
see https://github.com/livekit/client-sdk-js/pull/1512
=> Unorder the lossy data channel

Cargo.lock, Cargo.toml, livekit-api/Cargo.toml, livekit-ffi/Cargo.toml
=> bump livekit-api and livekit-ffi

livekit-api/src/access_token.rs
=> add attributes to Claims and AccessToken

examples/wgpu_room/Cargo.toml, livekit-ffi/Cargo.toml, webrtc-sys/Cargo.toml, webrtc-sys/build.rs, webrtc-sys/src/video_decoder_factory.cpp, webrtc-sys/src/video_encoder_factory.cpp, yuv-sys/Cargo.toml
and fixed build issue for ios sim.
=> chore: Optional flags for video hw codec.
