- .github/workflows/webrtc-builds.yml
- livekit-webrtc/src/native/peer_connection.rs
- livekit-webrtc/src/native/rtp_parameters.rs
- livekit-webrtc/src/native/rtp_transceiver.rs
- livekit-webrtc/src/peer_connection.rs
- webrtc-sys/build.rs
- webrtc-sys/libwebrtc/.gitignore
- webrtc-sys/libwebrtc/build_linux.sh
- webrtc-sys/libwebrtc/build_macos.sh
- webrtc-sys/libwebrtc/build_windows.cmd
- Doing jobs in parallels in [GHA](https://github.com/theomonnom/client-sdk-rust/actions/runs/4765787387/jobs/8471968034) (Divide build time by 3).
- Now use custom webrtc builds for this repo
- Windows crashes when receiving video is now fixed (thanks @cloudwebrtc)
- Now reading defines from webrtc.ninja
- Added a small create_pc test to be sure libwebrtc is working/linked correctly 
- Fix MacOS builds 
- Fixed Linux duplicated main build error (due to nasm)
Debug builds of webrtc are still not supported inside the Rust SDK (even if we're still building them). On Windows, Rust never links against libcmtd... (Pending/Draft [PR](https://github.com/rust-lang/libc/pull/3178)). Not tested for other platforms
> fix: windows crashes & builds

- livekit-ffi/build.rs
- livekit-protocol/build.rs
Adding this `protoc` option to the `prost` build fixes a build error I received when building in Ubuntu containers:
```
#0 117.3 error: failed to run custom build command for `livekit-protocol v0.1.0 (https://github.com/livekit/client-sdk-rust.git?rev=a5caf12#a5caf129)`
#0 117.3 
#0 117.3 Caused by:
#0 117.3   process didn't exit successfully: `/usr/src/rtsp-publisher/target/release/build/livekit-protocol-11624bcec5533409/build-script-build` (exit status: 1)
#0 117.3   --- stderr
#0 117.3   Error: Custom { kind: Other, error: "protoc failed: livekit_room.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }
```
I didn't see the issue on Mac, but the build is still working with the change.
> Add proto3 optional to prost build

- examples/wgpu_room/src/sine_track.rs
- livekit-webrtc/src/native/audio_source.rs
libwebrtc (audio sources) doesn't seem to work with other frame sizes?
otherwise the publication fails, seems like the packets are ignored
> fix: different audio frame size than 10ms

- .github/workflows/builds.yml
- .github/workflows/ffi-builds.yml
- Cargo.lock
- livekit-ffi/Cargo.toml
- livekit/Cargo.toml
be more flexible, rustls doesn't work on windows aarch64 (waiting for ring 0.17)
this should fix the ffi builds and the CI
> feat: tls features 

- livekit-webrtc/src/native/peer_connection_factory.rs
- livekit-webrtc/src/peer_connection.rs
- webrtc-sys/include/livekit/data_channel.h
- webrtc-sys/include/livekit/peer_connection.h
- webrtc-sys/include/livekit/peer_connection_factory.h
- webrtc-sys/include/livekit/webrtc.h
- webrtc-sys/src/data_channel.cpp
- webrtc-sys/src/peer_connection.cpp
- webrtc-sys/src/peer_connection_factory.cpp
- webrtc-sys/src/webrtc.cpp
- Fix datachannel deadlock on dispose
- Fix audio device being disposed on the wrong thread
- Allow multiple RtcRuntime to be created (Useful for unit tests where we use multiple PeerConnectionFactory)
> fix: datachannel deadlocks & dispose crashes

- Cargo.lock
- livekit-ffi/Cargo.toml
- livekit-ffi/src/lib.rs
- livekit-ffi/src/server/audio_frame.rs
- livekit-ffi/src/server/mod.rs
- livekit-ffi/src/server/room.rs
- livekit-ffi/src/server/video_frame.rs
- livekit/src/rtc_engine/rtc_session.rs
- reduce lock times with scopes on some requests
- support tokio-console for tasks debugging on the ffi with the `tracing` feature flag 
This will print an error on the console if we detect a blocking callback. (Default to 2s)
> feat: warn blocking callbacks

- livekit-webrtc/src/native/rtp_parameters.rs
- webrtc-sys/build.rs
- webrtc-sys/build/src/lib.rs
- webrtc-sys/include/livekit/rtp_transceiver.h
- webrtc-sys/include/livekit/video_frame.h
- webrtc-sys/src/peer_connection_factory.cpp
- webrtc-sys/src/rtp_parameters.cpp
- webrtc-sys/src/rtp_parameters.rs
- webrtc-sys/src/rtp_transceiver.cpp
- webrtc-sys/src/rtp_transceiver.rs
- webrtc-sys/src/video_decoder_factory.cpp
- webrtc-sys/src/video_encoder_factory.cpp
- webrtc-sys/src/video_frame.cpp
- webrtc-sys/src/video_frame.rs
- use libwebrtc m114
enabled codecs atm: vp8 & h264
NOTE: This PR uses c++20 to fix some issues on Windows (The webrtc code use c++20 features like designated initializers).
For now the libwebrtc build scripts use c++17 for compiling, we will definitely need to change the scripts to use c++20 in the future. (see #129)
> feat: use libwebrtc m114

- webrtc-sys/libwebrtc/build_android.sh
- webrtc-sys/libwebrtc/build_ios.sh
- webrtc-sys/libwebrtc/build_linux.sh
- webrtc-sys/libwebrtc/build_macos.sh
- webrtc-sys/libwebrtc/build_windows.cmd
- webrtc-sys/libwebrtc/patches/add_deps.patch
I initially decided to go with:
`call lib.exe /OUT:"%ARTIFACTS_DIR%\lib\webrtc.lib" %OUTPUT_DIR%\obj\webrtc.lib %OUTPUT_DIR%\obj\media\rtc_simulcast_encoder_adapter\simulcast_encoder_adapter.obj`
but decided to pick a cleaner patch from https://github.com/shiguredo-webrtc-build/webrtc-build/blob/master/patches/add_deps.patch
my previous [commit](https://github.com/livekit/client-sdk-rust/commit/6f5b45690efc7bbdba4d1ae973f67ff17fcbafa8) was not sufficient
> fix: undefined symbols for simulcast adapter

- livekit-webrtc/src/data_channel.rs
- livekit-webrtc/src/native/data_channel.rs
- livekit/src/room/mod.rs
- livekit/src/room/participant/local_participant.rs
- livekit/src/room/publication/local.rs
- livekit/src/room/publication/mod.rs
- livekit/src/room/publication/remote.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_session.rs
- webrtc-sys/include/livekit/data_channel.h
- webrtc-sys/src/data_channel.cpp
- webrtc-sys/src/data_channel.rs
- correctly sync states after signal resume
- now using a "`LastInfo`" struct to store the last successful session states
- also fixed `LocalTrackPublication::track` returning `LocalTrack` instead of `Option<LocalTrack>`
- It was a wrong assumption
> feat: sync states after resume 

- .github/workflows/ffi-builds.yml
- explicit deployment target for macos
- better library naming
- use [manylinux](https://github.com/pypa/manylinux) (increase linux compatibility). good practice from the Python community
- currently using `manylinux2014`
related PR was #147 but it was not sufficient
> ci: improved ffi builds 

- livekit-ffi/protocol/audio_frame.proto
- livekit-ffi/protocol/video_frame.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/audio_stream.rs
- livekit-ffi/src/server/video_stream.rs
This will allow us to make sure we're not leaking any memory by ignoring some ffi events while closing too early
> feat: add eos events

- Cargo.lock
- Cargo.toml
- examples/Cargo.lock
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/server/requests.rs
- livekit/Cargo.toml
- livekit/src/room/mod.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/peer_transport.rs
- livekit/src/rtc_engine/rtc_session.rs
- fix publisher offer being sent before the SyncState (This caused the migration to fail/incorrect state)
- ~~add RtcConfiguration to the FFI server~~ another PR
- wait for subscriber pc on initial connection
> fix: publisher migration failures

- examples/Cargo.lock
- livekit-ffi/protocol/e2ee.proto
- livekit-ffi/src/conversion/room.rs
- livekit-ffi/src/livekit.proto.rs
- livekit-webrtc/src/native/frame_cryptor.rs
- livekit-webrtc/src/native/peer_connection_factory.rs
- livekit/src/room/e2ee/key_provider.rs
- livekit/src/room/e2ee/manager.rs
- livekit/src/room/mod.rs
- webrtc-sys/build/src/lib.rs
- webrtc-sys/include/livekit/frame_cryptor.h
- webrtc-sys/include/livekit/peer_connection_factory.h
- webrtc-sys/src/frame_cryptor.cpp
- webrtc-sys/src/frame_cryptor.rs
https://github.com/livekit/client-sdk-rust/releases/tag/webrtc-6af5bfd
> fix: e2ee and upgrade webrtc

- webrtc-sys/src/webrtc.cpp
Fix https://github.com/livekit/client-sdk-rust/issues/192
> fix: support non-utf8 std::string which can come e.g. from Windows message errors

- .github/workflows/ffi-builds.yml
- .github/workflows/webrtc-builds.yml
- livekit-ffi/.gitignore
- livekit-ffi/build.rs
Time is precious. (and even slower with a bad connection)
Add the webrtc + livekit licenses with the builds (Wasn't there before..)
> feat: automatically release drafts for ffi & add license 

- livekit-ffi/src/server/room.rs
- livekit/src/room/mod.rs
- livekit/src/room/publication/remote.rs
- Handle the case a remote participant Sid can change
- Don't create a new participant if the state of the new one is already disconnected (e.g)
` [2023-09-25T23:23:31Z INFO  livekit::room] participant update: [ParticipantInfo { sid: "PA_3DH5jgnRV8NA", identity: "client", state: Disconnected, tracks: [], metadata: "", joined_at: 1695684209, name: "", version: 3, permission: Some(ParticipantPermission { can_subscribe: true, can_publish: true, can_publish_data: true, can_publish_sources: [], hidden: false, recorder: false, can_update_metadata: false }), region: "sfo3", is_publisher: false }]`
> fix: participant updates

- livekit/src/rtc_engine/rtc_session.rs
- It seems that SetRemoteDescription gets into a stuck state if we try to close the peer connections at the same time?
cc @cloudwebrtc
> fix: tasks being stuck while closing the PC

- libwebrtc/src/data_channel.rs
- livekit-api/src/signal_client/mod.rs
- livekit-ffi/src/server/room.rs
- livekit/Cargo.toml
- livekit/src/room/mod.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_events.rs
- livekit/src/rtc_engine/rtc_session.rs
- Refactor session reconnection
- We now have access to the current `RtcSession` even when reconnecting. (Because it is not locked while reconnecting).
This allow us to get the PC stats at whatever moment. This also change the fact that multiple operations can happens at the same time (send_data, create a new sender, remove a sender).
Some operations doesn't require the reconnection to be finished (e.g removing a sender)
- RtcSession is not an `Option` anymore (Always present but can't be in a unconnected state)
The pattern is done in a manner where you can't do actions on a RtcSession without thinking about the reconnection logic
> fix: better reconnection logic & safety

- livekit-ffi/protocol/room.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/room.rs
- livekit/src/room/mod.rs
- livekit/src/room/participant/local_participant.rs
- livekit/src/room/participant/mod.rs
- livekit/src/room/participant/remote_participant.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_session.rs
both, participant and room metadata
> feat: handle metadata

- Cargo.lock
- livekit-ffi/protocol/ffi.proto
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/requests.rs
- livekit-ffi/src/server/room.rs
> feat: ffi update metadata requests

- Cargo.lock
- livekit-api/src/signal_client/mod.rs
- livekit-api/src/signal_client/signal_stream.rs
> fix: relative /rtc & remove sensitive logs

- livekit-api/src/signal_client/mod.rs
seems like this is already supported by the Rust SDK
https://github.com/livekit/client-sdk-js/pull/605/files
> feat: bump to protocol 9

- Cargo.lock
- livekit-api/src/signal_client/mod.rs
- livekit/src/room/mod.rs
swallow for now, buffering will need to synchronize the future data to keep the order
> fix: swallow data when the participant info is unknown 

- libwebrtc/src/native/video_frame.rs
- libwebrtc/src/video_frame.rs
- livekit-ffi/protocol/video_frame.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/requests.rs
- livekit-ffi/src/server/video_source.rs
- webrtc-sys/include/livekit/video_frame_buffer.h
- webrtc-sys/src/video_frame_buffer.cpp
- webrtc-sys/src/video_frame_buffer.rs
This allow to use external data as src (e.g Python buffer)
Not every conversion is support atm. (Only I420)
> feat: allow conversions using ptr on the ffi

- livekit-ffi/src/server/requests.rs
So we're not following FourCC as it is confusing for users?
But instead we follow the logic from OpenCV etc
> rename rgba conversions

- livekit/src/room/options.rs
- livekit/src/room/participant/local_participant.rs
fixes https://github.com/livekit/python-sdks/issues/119
> fix: appropriate encoding

- livekit-ffi/protocol/ffi.proto
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/requests.rs
- livekit/src/room/mod.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_session.rs
expose stats of PCs (tracks are already exposed)
> expose session stats

- livekit-ffi/src/server/room.rs
Instead of panic, it'll send an error on the Python side
> ffi: fix panic when publishing data while room is closed

- .github/workflows/builds.yml
- .github/workflows/gen-protocol.yaml
- Cargo.lock
- livekit-protocol/Cargo.toml
- livekit-protocol/src/livekit.rs
- livekit-protocol/src/livekit.serde.rs
Also added CI for protocol gen
> Updated protocol to v1.9.9

- livekit-ffi/protocol/room.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/room.rs
This is a breaking change, because I had to disable the `DataReceived` message. Otherwise caller will get two messages with the same data (old and new protocol). I hope removing all fields is enough to trigger an error on the target language SDK side during build, so that the author can update it to using `DataPacketReceived` message.
> New FFI for data packets. Support receiving DTMF.

- webrtc-sys/src/audio_device.cpp
Hardcoded:
```
kBytesPerSample = 2;
kChannels = 2;
```
Does not follow webrtc assert in `AudioTransportImpl::NeedMorePlayData`:
```
RTC_DCHECK_EQ(sizeof(int16_t) * nChannels, nBytesPerSample);
```
so the fix follows the same convention as we have in webrtc ` AudioDeviceBuffer::RequestPlayoutData`:
```
const size_t bytes_per_frame = play_channels_ * sizeof(int16_t);
```
> Fix hardcoded kBytesPerSample

- Cargo.lock
- libwebrtc/Cargo.toml
- libwebrtc/src/audio_stream.rs
- libwebrtc/src/native/audio_stream.rs
- libwebrtc/src/native/peer_connection_factory.rs
- libwebrtc/src/native/video_stream.rs
- libwebrtc/src/video_stream.rs
- livekit-runtime/Cargo.toml
- livekit-runtime/src/async_std.rs
- livekit-runtime/src/dispatcher.rs
- livekit-runtime/src/tokio.rs
This is a follow-up to https://github.com/livekit/rust-sdks/pull/310
When building the main `livekit` crate the `async` or `dispatcher` features  (as opposed to the default `tokio` feature), we already have a dependency on the `futures` crate, which provides the `Stream` trait, so we don't need a dependency on `tokio-stream`.
As a drive-by, I fixed a test that was failing in CI due to a  missing `tokio` runtime, by applying the `tokio::test` macro to that test (which sets up a tokio runtime automatically).
> Avoid tokio-stream dependency when using a runtime other than tokio

- libwebrtc/src/native/video_frame.rs
- libwebrtc/src/native/video_source.rs
- libwebrtc/src/video_frame.rs
- webrtc-sys/build.rs
- webrtc-sys/include/livekit/video_frame_buffer.h
- webrtc-sys/src/objc_video_frame_buffer.mm
- webrtc-sys/src/video_frame_buffer.cpp
- webrtc-sys/src/video_frame_buffer.rs
Depends on https://github.com/livekit/rust-sdks/pull/354 (this branch contains that change as well).
In the [Zed editor](https://github.com/zed-industries/zed), we're switching over from using the LiveKit [Swift SDK](https://github.com/livekit/client-sdk-swift) to this crate.  The main motivation is that we want our LiveKit-based screen-sharing and audio features to work on Linux (and someday Windows), not just macOS.
In order to implement screen sharing efficiently (as it was before, when using the Swift  SDK), we want to pass video frames directly from the `ScreenCaptureKit` framework to this crate's `NativeVideoSource::capture_frame` method, without copying them into intermediate buffers. Similarly, when playing remote video tracks, we want to take decoded video frames directly from …
> Add APIs for converting between native VideoFrameBuffers and their underlying `CVPixelBuffer` on macOS

- libwebrtc/src/native/video_source.rs
Follow-up to https://github.com/livekit/rust-sdks/pull/310
That PR added the ability to use async runtimes other than Tokio, via the `livekit-runtime` adapter crate. But this *one* direct usage of `tokio::time::interval` got left behind.
> Avoid direct use of tokio interval in rtc video source

- libwebrtc/src/audio_source.rs
- libwebrtc/src/native/audio_source.rs
- livekit-ffi/protocol/audio_frame.proto
- livekit-ffi/src/conversion/audio_frame.rs
- livekit-ffi/src/livekit.proto.rs
- webrtc-sys/src/audio_track.rs
This parameter is used to avoid queues and silence frames causing latency accumulation, and is typically used when connecting to Audio Capture devices or other real-time sources.
> Add enable_queue for AudioSourceOptions.

- .github/workflows/builds.yml
- .github/workflows/ffi-builds.yml
- .github/workflows/tests.yml
- .github/workflows/webrtc-builds.yml
In January 2024, GitHub announced the [deprecation of macOS 11](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) and the removal of the runner image by June 2024. The macOS 11 runner image will be removed on 6/28/2024. We recommend updating workflows to use macos-14, macos-13, macos-12, or macos-latest. Reminder emails will be sent to those who have used the macOS 11 runner image in the past 30 days. Jobs using macOS 11 will temporarily fail during scheduled time periods to raise awareness of the upcoming removal.
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal
> Upgrade macOS runners to `macos-13`.

- livekit/src/room/participant/mod.rs
- livekit/src/room/publication/local.rs
- livekit/src/room/track/local_audio_track.rs
- livekit/src/room/track/local_video_track.rs
- livekit/src/room/track/mod.rs
- livekit/src/room/track/remote_audio_track.rs
- livekit/src/room/track/remote_video_track.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_session.rs
fixes #358 (`ActiveSpeakersChanged` always got sent for me, this fixes the `Muted` issues)
tested with Zed's example, with rust-sdks on commit `ffi-v0.6.1~3` because some APIs changed since they made the example.
> livekit: send mute events to SFU

- livekit-ffi/protocol/ffi.proto
- livekit-ffi/protocol/participant.proto
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/conversion/participant.rs
- livekit-ffi/src/conversion/room.rs
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/requests.rs
- livekit-ffi/src/server/room.rs
- livekit-protocol/src/livekit.rs
- livekit-protocol/src/livekit.serde.rs
- livekit/src/room/mod.rs
- livekit/src/room/participant/local_participant.rs
- livekit/src/room/participant/mod.rs
- livekit/src/room/participant/remote_participant.rs
Also:
- rename update_name/attributes/metadata -> set_name/attributes/metadata for consistency with client-sdk-js
- add async getRoomSid to FFI
> Add participant attributes to the FFI

- livekit-ffi/protocol/ffi.proto
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/requests.rs
- livekit-ffi/src/server/room.rs
- livekit/src/prelude.rs
- livekit/src/room/mod.rs
- livekit/src/room/participant/local_participant.rs
implementation naming varies between `publish_dtmf` and `publish_sip_dtmf`. 
The intention was to use `publish_dtmf` on exposed APIs and `publish_sip_dtmf` for sdk-internal messaging.
Not sure anymore if that distinction makes any sense though.
> Add publish_dtmf

- livekit/src/room/mod.rs
- livekit/src/room/participant/mod.rs
Attribute diff logic didn't exactly match the behavior of client-sdk-js
Tested manually against python-sdk
> Fix attribute diff logic

- examples/api/Cargo.toml
- examples/basic_room/Cargo.toml
- examples/basic_room/src/main.rs
- examples/basic_room_async/Cargo.toml
- examples/basic_room_dispatcher/Cargo.toml
- examples/mobile/Cargo.toml
- examples/mobile/src/lib.rs
- examples/play_from_disk/Cargo.toml
- examples/save_to_disk/Cargo.toml
- examples/save_to_disk/src/main.rs
- examples/webhooks/Cargo.toml
- examples/wgpu_room/Cargo.toml
- examples/wgpu_room/src/app.rs
- examples/wgpu_room/src/service.rs
- examples/wgpu_room/src/sine_track.rs
changes:
Since the examples use directories as dependencies, they should always correspond to the livekit api version, so the version field is removed from all examples' Cargo.toml
close https://github.com/livekit/rust-sdks/issues/380
Just tested, basic_room and wgpu_room are working again.
> Fix broken examples.

- libwebrtc/Cargo.toml
- livekit/Cargo.toml
- webrtc-sys/Cargo.toml
- webrtc-sys/build/Cargo.toml
webrtc-sys didn't get bumped, so now libwebrtc is angry.
> patch bump webrtc-sys and dependents

- Cargo.lock
- livekit-ffi/Cargo.toml
- livekit-ffi/src/server/room.rs
this already led to wrong behaviour, we're just adding an error before that happens.
> ffi: force VideoEncoding bitrate and framerate

- livekit/src/room/mod.rs
This is confusing to be logged at the Rust layer.
> Remove unexpected close error message

- livekit/Cargo.toml
tagging this commit `v0.5.2` when merged for CI and crates.io
> actually bump livekit to 0.5.2

- webrtc-sys/libwebrtc/boringssl_prefix_symbols.txt
apparently objcopy doesn't allow whitespace lines 🤦‍♀️
> fix comment for boringssl_prefix_symbols.txt

- livekit/src/room/options.rs
- livekit/src/room/participant/local_participant.rs
Users prefer FullBand audio by default. In most cases this gives a clear boost in both voice and audio quality.
> Increase default audio bitrates

- webrtc-sys/include/livekit/audio_track.h
- webrtc-sys/src/audio_track.cpp
old
new
also fix buffer reserving space using resize `instead` of `reserve` method
> send silence frames on the AudioSource when the queue is empty

- livekit-api/src/signal_client/mod.rs
- livekit-api/src/signal_client/signal_stream.rs
- livekit/src/rtc_engine/rtc_session.rs
- avoid reconnection on normal room close (+ avoid logs)
- avoid double logs on reconnect
> fix: avoid wrong reconnection logs 

- livekit-ffi/src/server/mod.rs
this was making hard to sync handles with the ffi client (the client were still trying to dispose the handles after dispose)
> don't drop handles on dispose

- webrtc-sys/build.rs
Neither X or OpenGL related libraries are needed for livekit sdk to work in the client code.
When trying to use LiveKit Rust SDK in Zed, its Linux build fails with 
https://github.com/zed-industries/zed/actions/runs/11149886429/job/30989794892?pr=13343#step:7:768
```
= note: mold: library not found: GL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
which is "expected": Zed does not support OpenGL backend, using Vulkan instead.
Due to this, it does not make any sense to link with it, and it seems that neither examples I've tried checking need that?
Happy to revisit the removal list after someone with more context explains it better.
> Avoid extra dylib dependencies

- livekit-ffi/src/server/room.rs
This looked like a bug/oversight that I found while working on RPC. It's also getting flagged by the build (unused vars) but we have a pretty noisy build log so its drowned out.
> await transcription and dtmf handles on room close

- webrtc-sys/build.rs
- webrtc-sys/include/livekit/prohibit_libsrtp_initialization.h
- webrtc-sys/src/lib.rs
- webrtc-sys/src/prohibit_libsrtp_initialization.cpp
- webrtc-sys/src/prohibit_libsrtp_initialization.rs
This allows for applications to intialize `libsrtp` for their own direct use, without `libwebrtc` later breaking because it can't initialize `libsrtp`)
> expose libwebrtc's ProhibitLibsrtpInitialization

- Cargo.lock
- livekit-api/src/services/twirp_client.rs
The twirp client overwrites the URL path, which can lead to unexpected behavior. This was already fixed for other parts of the code base (https://github.com/livekit/rust-sdks/issues/217).
> fix: don't overwrite the url path in twirp-client

- livekit-api/src/services/mod.rs
The `ServiceError` that is returned by various API calls has a `Twirp` variant containing a private `TwirpError`. This PR re-exports the `TwirpError` and its related types, making them public.
> fix: re-export twirp error types

- webrtc-sys/src/jsep.cpp
This was causing crashes [here](https://github.com/zed-industries/zed/blob/76936fa5b44103136375a823e5b76476ae82683e/crates/live_kit_client/examples/test_app.rs#L106) in Zed's live kit test app when run on Linux.
> Use rust::String::lossy for stringification to avoid crashing due to non-utf8 content

- livekit/src/room/options.rs
Fixes an issue with compute_appropriate_encoding, where the last preset in the list with the highest FPS wasn't considered.
Changes the order in into_rtp_encodings to have the highest quality first.
> Fix enconding presets

- soxr-sys/Cargo.toml
Motivation for this is a bit of a corner case:
* Including a local checkout of livekit rust-sdks as a package
* Installing Zed from source. This requires licenses specified by all packages.
> Add license to `soxr-sys/Cargo.toml`

- livekit-ffi/build.rs
fix livekit-ffi build on ios failure
https://github.com/livekit/rust-sdks/actions/runs/12096245495/job/33730331197
```bash
thread 'main' panicked at livekit-ffi/build.rs:49:13:
Unsupported target, ios
```
> fix-livekit-ffi-build-on-ios-failure

- webrtc-sys/libwebrtc/build_windows.cmd
no idea why this only occurs on Windows, or why it only started appearing now. let's see if this fixes things
this does make the CI build process a little longer.
> ci: attempt to fix windows webrtc builds

- .github/workflows/publish.yml
i've enabled deploy keys and set them to override branch protections, then added this key to the environmental variable. this line should replace the SSH key used by nanpa to be this key, which has elevated permissions.
> ci: add deploy key to nanpa CI

- examples/play_from_disk/src/main.rs
This pull request fixes the `play_from_disk` example, which could not be compiled with the latest SDK codebase, similar to #528.
Additionally, the included WAV file (change-sophie.wav) contains unexpected chunks in its header, causing the parser to fail. I added logic to skip chunks until the data chunk is found.
With these two fixes, the example works correctly on my local environment.
> Fix `play_from_disk` example to work with recent SDK

- examples/save_to_disk/src/main.rs
This pull request fixes the issue described in #465.
The issue occurred because the example code was not updated to reflect recent changes in the SDK. To address this, I updated only the example code, leaving the SDK code unchanged. This ensures that the example works correctly with the latest SDK.
I have verified that the fix works as expected on my local environment.
```
Connected to room: test - RM_XbLs8ZcGkyXR
Recording track TrackSid("TR_AMPtcW3Rt7zTNZ")
Done
```
> Fix `save_to_disk` example to work with recent SDK

- .nanpa/bump-ffi.kdl
the previous nanpa bump didn't properly update livekit-ffi, due to a nanparc/Cargo.toml mismatch.
> bump livekit-ffi to 0.12.4

- .nanpa/bump-ffi.kdl
Including fix for deadlock in nested RPC calls: #532
> bump livekit-ffi to 0.12.5

- .nanpa/free-stream-handles-when-room-is-closed.kdl
- Cargo.lock
- livekit-ffi/src/server/mod.rs
- livekit-ffi/src/server/requests.rs
- livekit-ffi/src/server/room.rs
As shown in [this test script](https://gist.github.com/typester/4907bebe022ffd429eeb27eeb392b1ec), it seems that if the FFI client forgets to close Audio/Video Stream on their side, a memory leak occurs.
Looking at the Python-side code, the `__del__` method is supposed to dispose of FFI handles when objects like VideoStream are released. However, for some reason, in this test script, that part is not invoked, leaving the handles unclosed.
In this pull request, the `FfiRoom` is modified to automatically dispose of associated track handles when it is closed.
With the script mentioned above, after running it, the memory consumption of the test process decreased from around 110MB to about 80MB, indicating the change is effective. 
(The test was conducted in a local environment using a …
> Close track FFI handles automatically when a FfiRoom is closed.

- .nanpa/bump-webrtc-sys.kdl
- Cargo.lock
- libwebrtc/Cargo.toml
In #545, I bumped the version of the `libwebrtc` crate but not the `webrtc-sys` crate. However, both needed to be bumped.
To fix this issue, I will bump webrtc-sys and re-bump libwebrtc to depend on the newer version of webrtc-sys.
> Fix webrtc crate build issue

- .nanpa/bump-protocol.kdl
- Cargo.lock
Current released version of livekit-protocol depends old version of livekit-runtime, and it causes build issue for crates that depends on livekit-protocol. Needs to be updated with latest dependency.
> bump livekit-protocol

- .github/workflows/builds.yml
updating images ahead of deprecation. updating all images, not just `ubuntu-20.04`.
https://github.com/actions/runner-images/issues/11101
> update builder runner images

- Cargo.lock
- livekit-protocol/src/promise.rs
Panic occurring in `Promise::try_result` is undesirable, so it has been replaced with RwLock to prevent panics.
>  Fix panic in Promise::try_result

- Cargo.lock
- livekit-ffi/.nanpa/rival-fang-bride.kdl
- livekit-ffi/Cargo.toml
Definitions of dependencies without specifying versions cause [a packaging issue](https://github.com/livekit/rust-sdks/actions/runs/13659444398/job/38186921358) in livekit-ffi. Using a workspace definition resolves this.
We don't use a published crate for FFI, so this doesn't block any releases of foreign language SDKs, but I will fix this just in case.
> Fix packaging issue in livekit-ffi

- .nanpa/candy-blimp-twice.kdl
- Cargo.lock
- livekit-ffi/src/server/audio_stream.rs
- livekit-ffi/src/server/room.rs
- livekit/src/plugin.rs
Mainly to update the room_id. In some cases, the room_id is empty when the AudioStream is initialized.
> Add a mechanism to update stream information for applied audio filters after AudioStream initialization

- .nanpa/i420_to_nv12.kdl
- libwebrtc/src/native/yuv_helper.rs
- webrtc-sys/include/livekit/yuv_helper.h
- webrtc-sys/src/yuv_helper.rs
Currently our graphics framework at Zed requires NV12 buffers, but using the high-quality VP8 codec, we receive I420 buffers from livekit.
It'd be nice to figure out how to avoid that (and have libwebrtc do whatever conversions are needed internally), but in the meantime we need to call this on the received data.
> Add i420_to_nv12

- Cargo.lock
- soxr-sys/src/rint.h
Remove FE_INVALID-based exception handling since FPU doesn't detect float-to-int overflows.  
Now that we perform explicit bounds checking, the exception-based path offers no performance benefit.  
Ensures safe and portable clipping behavior across all platforms.
> fix soxr: remove FE_INVALID optimization

- livekit-api/src/services/egress.rs
- livekit-api/src/services/sip.rs
- livekit-ffi/protocol/participant.proto
- livekit-ffi/protocol/track.proto
- livekit-ffi/src/conversion/participant.rs
- livekit-ffi/src/conversion/room.rs
- livekit-ffi/src/conversion/track.rs
- livekit-ffi/src/livekit.proto.rs
- livekit-protocol/src/livekit.rs
- livekit-protocol/src/livekit.serde.rs
- livekit/src/prelude.rs
- livekit/src/proto.rs
- livekit/src/room/data_stream/outgoing.rs
- livekit/src/room/participant/mod.rs
- livekit/src/room/publication/local.rs
- livekit/src/room/publication/mod.rs
- livekit/src/room/publication/remote.rs
- livekit/src/room/track/mod.rs
- livekit/src/room/track/remote_audio_track.rs
Main motivation is to get the new pre connect buffer AudioTrackFeature added for usage in https://github.com/livekit/agents/pull/2171
> Bump protocol to v1.37.1 and add audio_features handling

- livekit/src/room/participant/local_participant.rs
There is no point about reducing the timeout if we don't know the latency.. It's hardcoded to 2s. 
Fixes substraction overflow
> fix duration overflow

- examples/wgpu_room/Cargo.toml
- examples/wgpu_room/src/app.rs
- examples/wgpu_room/src/main.rs
- examples/wgpu_room/src/video_grid.rs
- examples/wgpu_room/src/video_renderer.rs
enabling 200% scaling (HiDPI) on Ubuntu for monitor will cause the following error and immediate crash.
`wl_surface#26: error 2: Buffer size (1630x45) must be an integer multiple of the buffer_scale (2)`
Upgrading to the latest dependencies can fix this issue.
> chore: Update dependencies for wgpu room.

- livekit-api/src/services/sip.rs
- livekit-api/src/signal_client/mod.rs
- livekit-ffi/protocol/participant.proto
- livekit-ffi/protocol/room.proto
- livekit-ffi/src/conversion/participant.rs
- livekit-ffi/src/conversion/room.rs
- livekit-ffi/src/livekit.proto.rs
- livekit-ffi/src/server/room.rs
- livekit-protocol/src/livekit.rs
- livekit-protocol/src/livekit.serde.rs
- livekit/src/proto.rs
- livekit/src/room/data_stream/outgoing.rs
- livekit/src/room/mod.rs
- livekit/src/room/participant/mod.rs
- livekit/src/rtc_engine/mod.rs
- livekit/src/rtc_engine/rtc_session.rs
giving clients other information about the room so they could receive all updates
also ensure that we pass through full participant updates, since sid is expected to change in certain situations (reconnect, move)
FYI @bcherry
> Expose room updates, support MoveParticipant (protocol 15)

- release-plz.toml
`release-plz` manages:
- generate changelogs
- tag ffi (to trigger existing release CI
- publish it to crates.io
Existing CI:
- triggered by tag created by release-plz
- build and release as the same way to current FFI release workflow
Note: we need to publish livekit-ffi to crates.io to make this work. I will do it before merging this
> add livekit-ffi to release-plz management

- .github/workflows/release.yml
It looks like the release-plz workflow doesn't trigger any `push` operation when it creates tags. So ffi-build doesn't be triggered by default. This pr fixes it.
> fix(release workflow): call ffi-build workflow after release

- .github/workflows/ffi-builds.yml
- .github/workflows/release.yml
Switch from `gh workflow run` to `workflow_call` because triggering `ffi-builds.yml` from `release.yml` via `gh` results in a 403 error somehow
> update workflows to use workflow_call

- examples/Cargo.lock
- examples/basic_text_stream/Cargo.lock
- examples/basic_text_stream/Cargo.toml
- examples/play_from_disk/Cargo.lock
- examples/play_from_disk/Cargo.toml
- examples/save_to_disk/Cargo.toml
Some of the examples do not enable one of the TLS features on the LiveKit crate. As a result, room connection fails when the HTTPs request to fetch region URLs is made. This PR adds the _native-tls_ feature to the LiveKit dependency on all examples that don't already enable a TLS feature.
Fixes #683
> Add TLS feature for all examples

- webrtc-sys/build.rs
- webrtc-sys/src/nvidia/h264_encoder_impl.cpp
Resolves CUDA_ERROR_INVALID_VALUE error caused by attempting to access the video buffer from GPU instead of CPU. Previous SDK hardware rendering attempts on GPU resulted in silent failures and blank image output. This PR corrects the buffer access issue.
> fix: hardware rendering

- .github/workflows/tests.yml
- Cargo.lock
- livekit/Cargo.toml
- livekit/src/room/mod.rs
- livekit/src/room/utils/mod.rs
- livekit/src/room/utils/ttl_map.rs
- livekit/src/room/utils/tx_queue.rs
- livekit/src/rtc_engine/rtc_events.rs
- livekit/src/rtc_engine/rtc_session.rs
- livekit/tests/common/mod.rs
- livekit/tests/data_channel_test.rs
**Summary of changes**:
- Implement data channel reliability improvements from other SDKs:
- livekit/client-sdk-js/pull/1546
- livekit/client-sdk-swift/pull/737
- Refactor handling of incoming data packets
- Take value enum out of packet to avoid large clones 
- Prefer packet level participant info fields over deprecated user packet fields
- Retain local participant info in session layer
- Ensure all outgoing data packets have their participant SID and identity fields set
- End-to-end testing: introduce testing with a LiveKit server
- Utilities for reading configuration from environment, creating multiple room connections
- Test case to evaluate reliable data channel performance
- Enable in CI (macOS and Linux only)
> Data channel reliability

- livekit/src/rtc_engine/rtc_session.rs
Participant SID and Identity were being set as empty since `.then_some(user.participant_sid)` would return `None` when original fields has some value (ie. not none)
> fix: apply original participant fields in data messages

- .github/workflows/builds.yml
Use `rustup target add` to replace `actions-rs/toolchain@v1` because the repo of this runner has been archived
https://github.com/actions-rs/toolchain
Aand added `workflow_dispatch:` to allow the Builds CI to be triggered manually
> Update Rust toolchain installation method

- Cargo.lock
- livekit/Cargo.toml
- livekit/tests/common/e2e.rs
- livekit/tests/data_channel_test.rs
- livekit/tests/data_stream_test.rs
- livekit/tests/room_test.rs
When testing with a local SFU, it takes significantly longer to receive the first participant update (0.9s on average compared to 0.000003s on cloud). As a result, some user packets received during the E2E reliability test will not be emitted since they cannot be associated with a remote participant, leading to test failure. To address this, the `test_rooms` utility now waits for participant visibility across all room connections before resolving.
Other minor changes:
- New tests to verify basic room connection.
- Tests now use the `test-log` crate to bootstrap logging during test execution.
> Fix intermittently failing E2E reliability test 

- .github/workflows/tests.yml
_libwebrtc_ outputs thousands of debug logs that aren't useful.
> Use info level for CI test logging

- webrtc-sys/src/audio_track.cpp
A change in the resampler API introduced in _libwebrtc_ m137 caused the output frame's `samples_per_channel_`  property to remain uninitialized. As a result, the length of the output slice was always calculated as zero, resulting in `NativeAudioStream` yielding audio frames without any sample data.
Note: This issue only occurs when resampling is required (i.e., when the sample rate or number of channels used to create the `NativeAudioStream` does not match the source).
> Fix empty audio frames after resample

- livekit/tests/README.md
- livekit/tests/audio_test.rs
- livekit/tests/common/e2e/audio.rs
- livekit/tests/common/e2e/mod.rs
Adds an end-to-end test to verify audio transfer between two participants by publishing a sine wave at a known frequency and detecting it on the subscriber side.
The test is parameterized by channel count and sample rate for both publisher and subscriber, ensuring correct behavior when resampling occurs.
Follow up to: #722
> E2E audio test

- webrtc-sys/build.rs
The webrtc-sys build script was using `Command::new("clang")` to discover compiler library paths. On a system with Homebrew's llvm package installed, this command could resolve to `/usr/local/bin/clang` instead of the required Xcode toolchain compiler.
This caused the script to pass incorrect library search paths to the linker, resulting in errors like:
```
ld: warning: search path '/usr/local/lib/clang/22/lib/darwin' not found
ld: library 'clang_rt.osx' not found
```
The fix is to change `Command::new("clang")` to `Command::new("cc")` within the `configure_darwin_sysroot` function in build.rs.
On macOS, `cc` is the system's default compiler alias and is guaranteed to respect the toolchain set by `xcode-select`. This ensures that even if other versions of clang are in the PATH, the build …
> Fix build failure on macOS for developers who have multiple clang installations 

- libwebrtc/src/native/video_frame.rs
- libwebrtc/src/video_frame.rs
- webrtc-sys/include/livekit/video_frame_buffer.h
- webrtc-sys/src/video_frame_buffer.cpp
- webrtc-sys/src/video_frame_buffer.rs
Exports VideoFrameBuffer::Scale for every buffer by extending the livekit::*Buffer types.
> Enable buffer scaling
